version: "3.1"
services:

    postgres:
      image: postgres:9.5-alpine
      container_name: postgres
      restart: unless-stopped
      volumes:
         - "./infra/pgsql/script:/docker-entrypoint-initdb.d"
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
      ports:
        - "5430:5432"
      networks:
        - app-network

    app:
      build:
        context: ./application
        dockerfile: ../infra/app/Dockerfile
      image: php:8.2
      container_name: app
      restart: unless-stopped
      tty: true
      environment:
        SERVICE_NAME: app
        SERVICE_TAGS: dev
      working_dir: /var/www
      networks:
        - app-network
      depends_on:
        - postgres
      command: sh -c "php artisan migrate && php-fpm"

    webserver:
      image: nginx:alpine
      container_name: webserver
      restart: unless-stopped
      tty: true
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./application:/var/www
        - ./infra/nginx/conf.d:/etc/nginx/conf.d
      networks:
        - app-network
      depends_on:
        - app

networks:
  app-network:
    driver: bridge
